// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://xwj5jyayprgazjpcy25pmneeoi.appsync-api.us-west-2.amazonaws.com/graphql',
          region: 'us-west-2',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-sib2x77isbf7dpruxmpfnpxgke'
        }
    }
};

export default config;